ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: es.${domain_name}
      paths:
          - path: /
  tls:
    - secretName: elasticsearch-tls
      hosts:
        - es.${domain_name}